---
# handlers file for freshrss
- name: Ensure MariaDB has started
  ansible.builtin.systemd:
    name: mariadb
    state: started
    enabled: yes

- name: Restart Apache
  ansible.builtin.systemd:
    name: apache2
    state: restarted