---
# handlers file for vikunja
- name: Ensure MariaDB has started
  ansible.builtin.systemd:
    name: mariadb
    state: started
    enabled: yes

- name: Restart Apache
  ansible.builtin.systemd:
    name: apache2
    state: restarted

- name: Start Vikunja
  ansible.builtin.systemd:
    name: vikunja
    state: started
